services:
  postgres:
    image: "postgres:latest"
    container_name: mcp-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
